### ISSUE TITLE
Regards

### ISSUE THREAD

**Issue by YoshuaNava** [mseln/aeplanner#4]
Hej @mseln,
(I just got an update via Daniel Duberg Github activity and wanted to say hi. Feel free to close this issue)

This package is great! Congrats. Hope everything is going well :D

(I'll test tagging @kholdcro @danielduberg)

Kind regards,
Yoshua

**Comment by mseln** [comment]
Hey Yoshua! 

Thanks! :D

Hope everything is going well in Zürich! :)

Best
Magnus
