### ISSUE TITLE
KTH-UAV doesn't work

### ISSUE THREAD

**Issue by yiyongrobotics** [mseln/aeplanner#7]
I find the simulator of the KTH-UAV doesn't work

**Comment by mseln** [comment]
Could you please specify the problem?
- What doesn't work? 
- What do you try to run?
- Do you get some error messages?
- Also which operating system are you using?

**Comment by yiyongrobotics** [comment]
> Could you please specify the problem?
> 
> * What doesn't work?
> * What do you try to run?
> * Do you get some error messages?
> * Also which operating system are you using?

we use our own PX4 simulator, and now use your algorithm just to explore the map. the octomap and the odm now are provided by our own method, but after I use ground-staion to take off the simulator drone, I can't switch the mode offboard using the ground-station, and the nodes like rrt, rpl_exploration doesnt work can't publish the setpoint. 

thanks a lot

**Comment by mseln** [comment]
Hmm, if you are using your own simulator I would write a new node instead of using rpl_exploration. 

The aeplanner node should work as long as the octomap is provided and the service called correctly. The same goes for the rrtplanner.

Could you provide the log output if you run into any further trouble?

**Comment by yiyongrobotics** [comment]
> Hmm, if you are using your own simulator I would write a new node instead of using rpl_exploration.
> 
> The aeplanner node should work as long as the octomap is provided and the service called correctly. The same goes for the rrtplanner.
> 
> Could you provide the log output if you run into any further trouble?

thanks a lot, now exploration can be set to offborad, but the parameters of the duration ac.waitForResult(ros::Duration(5)) and  (!aep_ac.waitForResult(ros::Duration(3))) now are problems. when first one is too short, the exploration won't start and won't publish the setpoint so that we can't set it to offboard. when the second one is too short, it always publishes the initial position so that it won't explore. and both are very difficult to tune to let it explore. is there any rule to tune both parameters.

**Comment by mseln** [comment]
Hmm, these are parameters that you never should need to tune! Something seems shady here... I will have to look into this.

**Comment by yiyongrobotics** [comment]
> Hmm, these are parameters that you never should need to tune! Something seems shady here... I will have to look into this.


first I launch the same nodes as the exploration.launch, and offboard the drone. If I won't change the parameters of the ros duration time in rpl_exploration.cpp, I check the topic setpoint (command to drone) and found no any msgs, I think the aeplanner didn't start. how to fix it?

**Comment by mseln** [comment]
There should be no tuning whatsoever of those parameters, the set point should be published continuously. I saw that it was published from two different nodes though and with no frame nor stamp. I have now made so that only FlyTo publishes poses with correct headers. The frame_id is hardcoded to map atm. If this solves it I will read it from the parameter file instead before merging it.

Please checkout `fix-fly-to-header`, try it again and tell me if it works.

**Comment by yiyongrobotics** [comment]
> There should be no tuning whatsoever of those parameters, the set point should be published continuously. I saw that it was published from two different nodes though and with no frame nor stamp. I have now made so that only FlyTo publishes poses with correct headers. The frame_id is hardcoded to map atm. If this solves it I will read it from the parameter file instead before merging it.
> 
> Please checkout `fix-fly-to-header`, try it again and tell me if it works.

sorry, it still doesn´t work and no set_point publishes.

**Comment by gouyiyong** [comment]
> There should be no tuning whatsoever of those parameters, the set point should be published continuously. I saw that it was published from two different nodes though and with no frame nor stamp. I have now made so that only FlyTo publishes poses with correct headers. The frame_id is hardcoded to map atm. If this solves it I will read it from the parameter file instead before merging it.
> 
> Please checkout `fix-fly-to-header`, try it again and tell me if it works.

/home/jordy/Pictures/Screenshot from 2019-06-28 14-23-35.png

**Comment by gouyiyong** [comment]
> There should be no tuning whatsoever of those parameters, the set point should be published continuously. I saw that it was published from two different nodes though and with no frame nor stamp. I have now made so that only FlyTo publishes poses with correct headers. The frame_id is hardcoded to map atm. If this solves it I will read it from the parameter file instead before merging it.
> 
> Please checkout `fix-fly-to-header`, try it again and tell me if it works.

/home/jordy/Pictures/Screenshot from 2019-06-28 14-23-35.png

**Comment by yiyongrobotics** [comment]
> There should be no tuning whatsoever of those parameters, the set point should be published continuously. I saw that it was published from two different nodes though and with no frame nor stamp. I have now made so that only FlyTo publishes poses with correct headers. The frame_id is hardcoded to map atm. If this solves it I will read it from the parameter file instead before merging it.
> 
> Please checkout `fix-fly-to-header`, try it again and tell me if it works.

![Screenshot from 2019-06-28 14-23-35](https://user-images.githubusercontent.com/26245593/60342042-b0bd4a80-99b0-11e9-9a85-c686eeb0cd48.png)

**Comment by mseln** [comment]
The problem seems to be that the fly_to_server crashes at lookupTransform, because the frame "map" does not exist. How does your tf tree look? Run: `rosrun rqt_tf_tree rqt_tf_tree` and export the image and post here.

**Comment by yiyongrobotics** [comment]
> The problem seems to be that the fly_to_server crashes at lookupTransform, because the frame "map" does not exist. How does your tf tree look? Run: `rosrun rqt_tf_tree rqt_tf_tree` and export the image and post here.

thanks a lot, now i have fixed it after modified the "map", and now wanna modify the exploration parameters to let it move slow and stable to improve the mapping quality. really appreciate your patient reply.

**Comment by mseln** [comment]
Great! I will make it read the `frame_id` from the parameterfile, before merging it to master.

Good luck!
